### PR TITLE
chore(package.json): add cross-env Set environment variables across p…

### PR DESCRIPTION
**Pull request by citrusjunoss**
…latforms

chore(package.json): add cross-env devDependencies Set environment variables across platforms

## PR Checklist

- [x] Fix linting errors
- [x] Label has been added

### CODE REVIEW

**Comment by citrusjunoss** [comment]
in windows thorw `export not an internal or external command ` when  `yarn  dev`

**Comment by unix** [comment]
Thanks!
And does the `build.sh` file need any improvement, on your current platform? (run `yarn build` to test it.)

**Comment by citrusjunoss** [comment]
> 谢谢！在当前平台上
> ，`build.sh`文件是否需要任何改进？（`yarn build`进行测试。）

The bash command and .sh script are not recognized by CMD or PowerShell.

**Comment by citrusjunoss** [comment]
> Thanks!
> And does the `build.sh` file need any improvement, on your current platform? (run `yarn build` to test it.)

The bash command and .sh script are not recognized by CMD or PowerShell.

**Comment by unix** [comment]
Current PR features are part of a compatible Windows. The content of this PR is not necessary if we are unable to do all the work on Windows for the time being.

If you really need to develop on Windows, I recommend you try `wsl2`.

**Comment by unix** [comment]
If it needs to be all Windows compatible, we might rewrite the script `build.sh`, but I haven't had much time to spend on open-source lately, so if you want to do that, let me know.
This PR will be closed, because partial content compatibility doesn't make sense. If you have a new point, please open a new PR / Issue.

**Pull request closed without merging**
